## 에러 처리를 해야하는 이유
- 예외적인 상황으로부터 프로그램의 안정성을 유지하기 위해 필요
- 에러가 적절하지 않으면 디버깅 시 찾기에 어려움이 존재

## try ... catch
- 오직 런타임 에러에만 동작 (즉, 실행 가능한 코드에만 동작)
- 동기적으로 동작, setTimeout 같이 스케쥴 된 코드에서 발생한 예외에는 사용 불가!

```
    // 만약 에러가 없다면 try 안의 코드 실행
    // 에러가 존재한다면 try 코드가 중단되고 catch 안의 코드 실행
    try {
        // 코드
    } catch (err) {
        // 에러 핸들링
    }
```

## throw
- 에러를 생성하는 연산자 (즉, 사용자가 예외를 정의할 수 있게 해줌)

```
    try {
        if (false) throw new SyntaxError("사용자 정의 에러"); 
        // 이 이후로는 코드가 진행되지 않는 다는 것을 기억
    } catch(e) {
        // 생략
    }
```

## instanceof
- 예상했던 에러인지 아닌지 확인하는 방법
- 변수나 값이 특정 객체의 인스턴스인지 유무를 반환해줌

```
    try {
        // 생략
    } catch (err) {
        if (err instanceof ReferenceError) console.log("에러 발생");
    }
```

## try ... catch ... finally
- 예외 처리 후 항상 실행하고 싶은 내용이 있다면 finally 사용하기

```
    try {
        // 코드
    } catch(err) {
        // 에러 핸들링
    } finally {
        // 항상 실행
    }
```